# Generated by Django 2.2.10 on 2025-02-26 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0021_auto_20231104_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='judge',
            name='is_dino',
            field=models.BooleanField(default=False),
        ),
    ]
