# Generated by Django 2.2.10 on 2024-11-29 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0021_auto_20231104_1847'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=255)),
                ('priority', models.DecimalField(decimal_places=2, max_digits=4)),
                ('color', models.CharField(default='#000000', max_length=7)),
            ],
        ),
        migrations.AddField(
            model_name='round',
            name='room_tag_priority',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='round',
            name='room_warning',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='round',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tab.Room'),
        ),
        migrations.AddField(
            model_name='judge',
            name='room_tags',
            field=models.ManyToManyField(blank=True, to='tab.RoomTag'),
        ),
        migrations.AddField(
            model_name='room',
            name='tags',
            field=models.ManyToManyField(blank=True, to='tab.RoomTag'),
        ),
        migrations.AddField(
            model_name='round',
            name='room_tags',
            field=models.ManyToManyField(blank=True, to='tab.RoomTag'),
        ),
        migrations.AddField(
            model_name='team',
            name='room_tags',
            field=models.ManyToManyField(blank=True, to='tab.RoomTag'),
        ),
    ]
