# Generated by Django 5.1 on 2025-03-07 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0022_alter_judge_name_alter_team_name'),
        ('tab', '0022_auto_20250227_0443'),
    ]

    operations = [
    ]
