# Generated by Django 5.0 on 2025-02-18 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0022_alter_breakingteam_id_alter_bye_id_alter_checkin_id_and_more'),
        ('tab', '0022_auto_20241221_2217'),
    ]

    operations = [
    ]
