# Generated by Django 2.2.10 on 2024-12-23 16:28

from django.db import migrations, models
from django.dispatch import receiver

from mittab.apps.tab.models import RoomTag
from django.db.models.signals import post_migrate


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0022_auto_20241221_2217'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=255)),
                ('priority', models.DecimalField(decimal_places=2, max_digits=4)),
                ('color', models.CharField(default='#000000', max_length=7)),
            ],
        ),
        migrations.AddField(
            model_name='judge',
            name='room_tags',
            field=models.ManyToManyField(blank=True, to='tab.RoomTag'),
        ),
        migrations.AddField(
            model_name='room',
            name='tags',
            field=models.ManyToManyField(blank=True, to='tab.RoomTag'),
        ),
        migrations.AddField(
            model_name='team',
            name='room_tags',
            field=models.ManyToManyField(blank=True, to='tab.RoomTag'),
        ),
    ]

@receiver(post_migrate)
def create_default_instance(sender, **kwargs):
    if not RoomTag.objects.filter(tag="Accessible").exists():
        RoomTag.objects.create(tag="Accessible", priority=99, color="#f8d7da")