# Generated by Django 5.0 on 2025-02-18 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0023_merge_20250218_2057'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=255)),
                ('priority', models.DecimalField(decimal_places=2, max_digits=4)),
                ('color', models.CharField(default='#000000', max_length=7)),
            ],
        ),
        migrations.AddField(
            model_name='judge',
            name='room_tags',
            field=models.ManyToManyField(blank=True, to='tab.roomtag'),
        ),
        migrations.AddField(
            model_name='room',
            name='tags',
            field=models.ManyToManyField(blank=True, to='tab.roomtag'),
        ),
        migrations.AddField(
            model_name='team',
            name='room_tags',
            field=models.ManyToManyField(blank=True, to='tab.roomtag'),
        ),
    ]
