# Generated by Django 5.0 on 2025-02-20 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0024_roomtag_judge_room_tags_room_tags_team_room_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judge',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
