# Generated by Django 5.0 on 2025-02-21 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0025_alter_judge_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
