from django.conf.urls import url
from mittab.apps.tab.views import pairing_views

urlpatterns = [    
    url(r"^pairings/status/$", pairing_views.view_status, name="view_status"),
    url(r"^pairings/view_rounds/$",
        pairing_views.view_rounds,
        name="view_rounds"),
    url(r"^round/(\d+)/$", pairing_views.view_round, name="view_round"),
    url(r"^round/(\d+)/stats/$", pairing_views.team_stats, name="team_stats"),
    url(r"^round/(\d+)/result/$",
        pairing_views.enter_result,
        name="enter_result"),
    url(r"^round/(\d+)/result/(\d+)/$",
        pairing_views.enter_multiple_results,
        name="enter_multiple_results"),
    url(r"^round/(\d+)/alternative_judges/(\d+)/$",
        pairing_views.alternative_judges,
        name="round_alternative_judges"),
    url(r"^round/(\d+)/(\d+)/alternative_teams/(gov|opp)/$",
        pairing_views.alternative_teams,
        name="round_alternative_teams"),
    url(r"^round/(\d+)/alternative_judges/$",
        pairing_views.alternative_judges,
        name="alternative_judges"),
    url(r"^round/(\d+)/alternative_rooms/$",
        pairing_views.alternative_rooms,
        name="alternative_rooms"),
    url(r"^round/(\d+)/alternative_rooms/(\d+)$",
        pairing_views.alternative_rooms,
        name="alternative_rooms"),
    url(r"^round/(\d+)/assign_judge/(\d+)/$",
        pairing_views.assign_judge,
        name="assign_judge"),
    url(r"^pairings/assign_team/(\d+)/(gov|opp)/(\d+)/$",
        pairing_views.assign_team,
        name="assign_team"),
    url(r"^round/(\d+)/assign_judge/(\d+)/(\d+)/$",
        pairing_views.assign_judge,
        name="swap_judge"),
        url(r"^round/(\d+)/assign_room/(\d+)/$",
        pairing_views.assign_room,
        name="assign_room"),
    url(r"^round/(\d+)/assign_room/(\d+)/(\d+)/$",
        pairing_views.assign_room,
        name="swap_judge"),
    url(
        r"^pairings/room_tag_warnings/(\d+)/$",
        pairing_views.room_tag_warnings,
        name="room_tag_warnings"
    ),
    url(r"^pairing/pair_round/$", pairing_views.pair_round, name="pair_round"),
    url(r"^pairing/assign_judges_to_pairing/$",
        pairing_views.assign_judges_to_pairing,
        name="assign_judges_to_pairing"),
    url(r"^pairing/assign_rooms_to_pairing/$",
        pairing_views.assign_rooms_to_pairing,
        name="assign_rooms_to_pairing"),
    url(r"^pairing/confirm_start_tourny/$",
        pairing_views.confirm_start_new_tourny,
        name="confirm_start_tourny"),
    url(r"^pairing/start_tourny/$",
        pairing_views.start_new_tourny,
        name="start_tourny"),
    url(r"^pairings/pairinglist/$",
        pairing_views.pretty_pair,
        name="pretty_pair"),
    url(r"^pairings/missing_ballots/$",
        pairing_views.missing_ballots,
        name="missing_ballots"),
    url(r"^pairings/pairinglist/printable/$",
        pairing_views.pretty_pair_print,
        name="pretty_pair_print"),
    url(r"^pairing/backup/$",
        pairing_views.manual_backup,
        name="manual_backup"),
    url(r"^pairing/release/$",
        pairing_views.toggle_pairing_released,
        name="toggle_pairing_released"),
    url(r"^pairing/view_backups/$",
        pairing_views.view_backups,
        name="view_backups"),
    url(r"^e_ballots/$", pairing_views.e_ballot_search,
        name="e_ballot_search"),
    url(r"e_ballots/(\S+)/$",
        pairing_views.enter_e_ballot,
        name="enter_e_ballot"),
    # Backups
    url(r"^backup/restore/(.+)/$",
        pairing_views.restore_backup,
        name="restore_backup"),
    url(r"^backup/download/(.+)/$",
        pairing_views.download_backup,
        name="download_backup"),
    url(r"^backup/(.+)/$", pairing_views.view_backup, name="view_backup"),
    url(r"^upload_backup/$", pairing_views.upload_backup,
        name="upload_backup"),
]